### ISSUE TITLE
Where can I find the django annotation file "all.anno"

### ISSUE THREAD

**Issue by felicitywang** [neulab/NL2code#1]
which appears in `evaluations.py`:
```
DJANGO_ANNOT_FILE = '/Users/yinpengcheng/Research/SemanticParsing/CodeGeneration/en-django/all.anno'
```
And some other such files with a given path [here](https://github.com/neulab/NL2code/search?utf8=%E2%9C%93&q=users%2F&type=). 

Thanks.

**Comment by neubig** [comment]
You can find the Django dataset here: http://ahclab.naist.jp/pseudogen/
And Hearthstone dataset here: https://github.com/deepmind/card2code
