### ISSUE TITLE
Code for dataset generation

### ISSUE THREAD

**Issue by tsdaemon** [neulab/NL2code#2]
Hi! I'm working on a similar model and I wanted to evaluate your model on another dataset (https://github.com/EdinburghNLP/code-docstring-corpus). Can you share the code for dataset generation?

**Comment by neubig** [comment]
You can find the Django dataset here: http://ahclab.naist.jp/pseudogen/
And Hearthstone dataset here: https://github.com/deepmind/card2code

**Comment by tsdaemon** [comment]
I am sorry for being inaccurate in the description of my issue. I do know, where to find the datasets you used for this model. But I need the code for their preprocessing to replicate all your experiment on another dataset. In README you give a link to a model ready binary files. I need somehow close the gap between raw and prepared data. And to be accurate in an evaluation, it is essential to use your preprocessing code instead of trying to figure it out by reverse engineering.

**Comment by neubig** [comment]
Gotcha, maybe @pcyin can help with this.

**Comment by tsdaemon** [comment]
I have found code in `dataset.py`, function `parse_django_dataset` probably is what I am looking for. Sorry for bothering you.

**Comment by pcyin** [comment]
Sorry for my late reply! Yes. This function transforms the original django dataset into a sequence of gold-standard actions used to train the model. Please feel free to reopen this issue if you have any questions :)
