### ISSUE TITLE
Ignore Theano UserWarnings about Gradient?

### ISSUE THREAD

**Issue by zhanwenchen** [neulab/NL2code#3]
I'm presenting your paper and demo your code for an ML class (for a grad-student-only assignment). Should I pay attention to the warnings below, given right before the actual training (printing epochs)?

I'm using

```
conda Python 2.7 environment
nltk 3.2.5
astor 0.6.2
vprof 0.36.1
theano 1.0.1+2.gcd195ed
```

> 02/27/2018 00:15:00 [INFO] code_gen: avg_action_num: 141
02/27/2018 00:15:00 [INFO] code_gen: grammar rule num.: 100
02/27/2018 00:15:00 [INFO] code_gen: grammar node type num.: 57
02/27/2018 00:15:00 [INFO] code_gen: source vocab size: 351
02/27/2018 00:15:00 [INFO] code_gen: target vocab size: 556
02/27/2018 00:15:01 [INFO] recurrent: applying dropout with p = 0.200000
02/27/2018 00:15:04 [INFO] recurrent: applying dropout with p = 0.200000
02/27/2018 00:15:05 [INFO] components: applying dropout with p = 0.200000
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:589: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: decoder_lstm_p4
  handle_disconnected(elem)
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:589: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: decoder_lstm_p10
  handle_disconnected(elem)
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:589: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: decoder_lstm_p16
  handle_disconnected(elem)
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:589: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: decoder_lstm_p22
  handle_disconnected(elem)
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:589: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: decoder_lstm_p29
  handle_disconnected(elem)
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:589: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: decoder_lstm_p30
  handle_disconnected(elem)
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:589: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: decoder_lstm_p31
  handle_disconnected(elem)
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:589: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: decoder_lstm_p32
  handle_disconnected(elem)
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:589: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: decoder_lstm_p33
  handle_disconnected(elem)
/Users/zhanwenchen/anaconda/envs/py27/lib/python2.7/site-packages/theano/gradient.py:615: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: <DisconnectedType>
  handle_disconnected(rval[i])

**Comment by pcyin** [comment]
Hi! It's fine. I remembered I created some unused nodes for attention over the decoded sequence `y_1 ... y_{t-1}`, which are not used in the final model. Sorry for the confusion :)
